# Logistic Regression using Least Squares Method

In [1]:
# Importing Libraries
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# Global Variables
BIAS = 1
ALPHA = 0.3
THRESHOLD = 0.5
EPOCHS = 1

In [3]:
# Dataset
x1 = [2.7810836, 1.4654894, 3.3965617, 1.3880702, 3.0640723,\
      7.6275312, 5.3324412, 6.9225967, 8.6754187, 7.6737565]
x2 = [2.550537, 2.3621251, 4.4002935, 1.8502203, 3.005306,\
      2.7592622, 2.0886268, 1.7710637, -0.242069, 3.508563]
Y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [4]:
# Logistic Function 
def h(x):
    return 1 / (1 + np.exp(-x))

In [5]:
# Prepare Inputs
X = []
for a, b in zip(x1, x2):
    temp = []
    temp.append(BIAS)
    temp.append(a)
    temp.append(b)
    X.append(temp)
X = np.array(X)
print(X.shape)
Y = np.array(Y)
print(Y.shape)

(10, 3)
(10,)


In [6]:
# Performing Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

In [7]:
# Initialize coefficient values and sharp prediction array
B = np.zeros((1,X.shape[1]))
sh_pred = np.zeros((Y.shape))

In [8]:
# Perform Logistic Regression using Least Squares Method
for _ in range(EPOCHS):
    for i in range(len(Y)):
        pred = h(np.sum(X[i] * B))
        B += (ALPHA * (Y[i] - pred) * pred * (1 - pred) * X[i])
        print(B)
        sh_pred[i] = 1 if pred >= THRESHOLD else 0
    print(sh_pred)
    print()

[[-0.0375     -0.10429064 -0.09564514]]
[[-0.0660511  -0.14613197 -0.16308641]]
[[-0.07716028 -0.18386498 -0.21197005]]
[[-0.09868803 -0.21374701 -0.25180114]]
[[-0.1067283  -0.23838299 -0.27596462]]
[[-0.08995788 -0.11046604 -0.22969061]]
[[-0.04844172  0.11091644 -0.14297885]]
[[-0.02104301  0.30058666 -0.09445399]]
[[-0.01973076  0.311971   -0.09477164]]
[[-0.01622585  0.33886677 -0.08247447]]
[1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]



In [9]:
# Showing Values
print("Coefficient Values")
print("b0\t\tb1\t\tb2")
print(*B, sep='\t')

Coefficient Values
b0		b1		b2
[-0.01622585  0.33886677 -0.08247447]


In [10]:
# Performing Predictions on X_test
Y_pred = []
for val in X_test:
    pred = h(np.sum(val * B))
    Y_pred.append(1 if pred >= THRESHOLD else 0)
print("Actual Output Values: ", end = '')
print(*Y_test)
print("Predicted Output Values: ", end = '')
print(*Y_pred)

Actual Output Values: 1 0
Predicted Output Values: 1 1


In [11]:
# Computing Accuracy Score
acc_score = accuracy_score(Y_test, Y_pred)
print("Accuracy Score:", acc_score)

Accuracy Score: 0.5
